### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by Krzychu92**
https://Krzychu92.github.io/js_promise_basic_DOM/

### CODE REVIEW

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Make sure to deploy your page and provide a link in the PR description

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Feel free to ask for help in the chat 
Screenshot 2024-01-23 at 15 38 42
The DEMO doesn't work

**Comment by Krzychu92** [comment]
Now it should work

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! Consider implementing this requirement 
Screenshot 2024-01-29 at 16 47 20

**Pull request closed without merging**
